export const moodList = [
    "---POSITIVE---",
    "happy",
    "excited",
    "energetic",
    "hopeful",
    "cheerful",
    "euphoric",
    "thrilled",
    "inspired",
    "confident",
    "determined",
    "grateful",
    "content",
    "proud",
    "satisfied",
    "loved",
    "affectionate",
    "trusting",
    "sympathetic",
    "caring",
    "relaxed",
    "serene",
    "peaceful",
    "calm",
    "cheerful",
    "---NEGATIVE---",
    "melancholic",
    "sad",
    "lonely",
    "unmotivated",
    "depressed",
    "gloomy",
    "guilty",
    "regretful",
    "heartbroken",
    "ashamed",
    "bitter",
    "disgusted",
    "angry",
    "mad",
    "frustrated",
    "jealous",
    "grumpy",
    "stubborn",
    "annoyed",
    "resentful",
    "vengeful",
    "hostile",
    "mischievous",
    "defiant",
    "bashful",
    "apathetic",
    "mistrustful",
    "---FEAR---",
    "shy",
    "anxious",
    "uncomfortable",
    "overwhelmed",
    "scared",
    "paranoid",
    "panicked",
    "fearful",
    "horrified",
    "devastated",
    "---NEUTRAL/COMPLEX---",
    "bored",
    "tired",
    "exhausted",
    "restless",
    "nervous",
    "tense",
    "nostalgic",
    "curious",
    "surprised",
    "shocked",
    "confused",
    "impatient",
    "disoriented",
    "insecure",
    "concerned",
    "embarrassed",
    "hopeful",
    "skeptical",
    "sarcastic",
    "flirty",
    "turned on",
    "dreamy",
    "neutral",
    "indifferent"
    ];

export const hasList = [
    "---ILLNESSES---",
    "has flu",
    "has fever",
    "has pneumonia",
    "has cold",
    "has food poisoning",
    "has epilepsy",
    "has panic attack",
    "has COVID-19",
    "has diabetes",
    "has sleep paralysis",
    "has cancer",
    "has hemorrhage",
    "has heart attack",
    "has diarrhea",
    "has stomach flu",
    "has paresis",
    "has brain tumor",
    "has brain damage",
    "has depression",
    "has migraines",
    "has asthma",
    "has bronchitis",
    "has allergies",
    "has arthritis",
    "has hypertension",
    "has anemia",
    "has kidney stones",
    "has appendicitis",
    "has tuberculosis",
    "has hepatitis",
    "has Lyme disease",
    "has shingles",
    "has insomnia",
    "has chronic fatigue",
    "has bipolar disorder",
    "has anxiety disorder",
    "has schizophrenia",
    "has dementia",
    "has stroke",
    "has ulcer",
    "has gout",
    "has thyroid disorder",
    "has eczema",
    "has psoriasis",
    "has mononucleosis",
    "has fibromyalgia",
    "has celiac disease",
    "has irritable bowel syndrome",
    "has osteoporosis",
    "has chronic pain",
    "has multiple sclerosis",
    "has Parkinson’s disease",
    "has lupus",
    "has endocarditis",
    "has diverticulitis",
    "has sciatica",
    "has vertigo",
    "has conjunctivitis",
    "has strep throat",
    "has sinusitis",
    "has urinary tract infection",
    "has meningitis",
    "has gastritis",
    "has hypoglycemia",
    "has hyperthyroidism",
    "has hypothyroidism",
    "has chronic bronchitis",
    "has emphysema",
    "has gallstones",
    "has tendonitis",
    "has carpal tunnel syndrome",
    "---BODY STATES---",
    "is drunk",
    "is overfed",
    "is pregnant",
    "is paralyzed",
    "is unconscious",
    "is on a diet",
    "is in heat",
    "has low mood",
    "has a period",
    "has an erection",
    "has a boner",
    "experiences premature ejaculation",
    "feels wetness inside",
    "is dehydrated",
    "is exhausted",
    "is nauseous",
    "is dizzy",
    "is in pain",
    "is feverish",
    "is sweating profusely",
    "is shivering",
    "is hungry",
    "is thirsty",
    "is sleep-deprived",
    "is hyperactive",
    "is lethargic",
    "is disoriented",
    "is bleeding",
    "is bruised",
    "is sunburned",
    "is frostbitten",
    "is overheated",
    "is hypothermic",
    "is in shock",
    "is cramping",
    "is bloated",
    "is constipated",
    "is delirious",
    "is trembling",
    "is lightheaded",
    "is aching",
    "is fatigued",
    "is disheveled",
    "is itching",
    "is swollen",
    "is breathless",
    "is overheated from exercise",
    "is chilled",
    "is hungover",
    "is jet-lagged",
    "is overstimulated",
    "is numb",
    "is tense",
    "is sweating nervously",
    "is experiencing heart palpitations",
    "is feeling faint",
    "is experiencing muscle spasms",
    "is feeling jittery",
    "---DESIRES---",
    "wants money",
    "wants love",
    "wants attention",
    "wants success",
    "wants happiness",
    "wants power",
    "wants revenge",
    "wants freedom",
    "wants adventure",
    "wants to learn something",
    "wants to travel the world",
    "wants to start a family",
    "wants to have sex",
    "wants recognition",
    "wants security",
    "wants peace",
    "wants fame",
    "wants respect",
    "wants friendship",
    "wants knowledge",
    "wants creativity",
    "wants independence",
    "wants luxury",
    "wants to make a difference",
    "wants to be remembered",
    "wants to achieve a goal",
    "wants to explore new places",
    "wants to improve health",
    "wants to find purpose",
    "wants to reconnect with someone",
    "wants to master a skill",
    "wants to experience joy",
    "wants to overcome fear",
    "wants to feel fulfilled",
    "wants to create art",
    "wants to build something",
    "wants to inspire others",
    "wants to be admired",
    "wants to find closure",
    "wants to live simply",
    "wants to achieve balance",
    "wants to pursue a passion",
    "wants to gain wisdom",
    "wants to leave a legacy",
    "wants to experience thrill",
    "wants to heal emotionally",
    "wants to find inner peace",
    "wants to be understood",
    "wants to feel secure",
    "wants to embrace change",
    "---NEEDS---",
    "needs to pee",
    "needs to evacuate",
    "needs food and water",
    "needs shelter",
    "needs sleep",
    "needs medical attention",
    "needs companionship",
    "needs guidance",
    "needs stability",
    "needs excitement",
    "needs adventure",
    "needs to feel needed",
    "needs to feel important",
    "needs someone to cry on",
    "needs rest",
    "needs safety",
    "needs warmth",
    "needs hygiene",
    "needs exercise",
    "needs mental stimulation",
    "needs emotional support",
    "needs financial security",
    "needs validation",
    "needs privacy",
    "needs purpose",
    "needs relaxation",
    "needs trust",
    "needs clarity",
    "needs time alone",
    "needs physical touch",
    "needs self-expression",
    "needs to be heard",
    "needs to feel safe",
    "needs to feel valued",
    "needs acceptance",
    "needs encouragement",
    "needs routine",
    "needs freedom",
    "needs respect",
    "needs reassurance",
    "needs intellectual challenge",
    "needs emotional connection",
    "needs personal space",
    "needs self-care",
    "needs recognition",
    "needs to feel empowered",
    "needs to feel included",
    "needs to feel accomplished",
    "needs closure",
    "needs to feel inspired",
    "---REASONS TO SAY NO---",
    "doesn't have enough money",
    "is too tired",
    "is too busy",
    "doesn't know how to do something",
    "is afraid of something",
    "dislikes something",
    "has a fear of failure",
    "has a fear of success",
    "is experiencing self-doubt",
    "is feeling overwhelmed",
    "is physically unwell",
    "is emotionally drained",
    "has prior commitments",
    "lacks confidence",
    "is morally opposed",
    "is avoiding conflict",
    "is protecting privacy",
    "is distrustful",
    "is under pressure",
    "is feeling anxious",
    "is recovering from trauma",
    "is avoiding risk",
    "is respecting boundaries",
    "is prioritizing health",
    "is concerned about safety",
    "is unprepared",
    "is distracted",
    "is grieving",
    "is feeling insecure",
    "is financially strained",
    "is emotionally unavailable",
    "is mentally exhausted",
    "is avoiding judgment",
    "is protecting energy",
    "is feeling unmotivated",
    "is overwhelmed by stress",
    "is dealing with family issues",
    "is prioritizing personal goals",
    "is avoiding overcommitment",
    "is feeling inadequate",
    "is respecting personal values",
    "is wary of consequences",
    "is feeling uncertain",
    "is avoiding embarrassment",
    "is focusing on recovery",
    "is preserving mental health",
    "is honoring a promise",
    "is avoiding unnecessary effort",
    "---RANDOM LIFE EVENTS---",
    "lost job",
    "won the lottery",
    "got robbed",
    "got beaten",
    "got divorced",
    "got married",
    "had an accident",
    "caused an accident",
    "meet someone",
    "was involved in a scandal",
    "had a near-death experience",
    "found out that they were adopted",
    "was diagnosed with a serious illness",
    "suffered from a traumatic event",
    "has been forced to do something they didn't want to",
    "dies",
    "moved to a new city",
    "started a new job",
    "graduated from school",
    "bought a house",
    "lost a loved one",
    "adopted a pet",
    "traveled abroad",
    "started a business",
    "went bankrupt",
    "survived a natural disaster",
    "became a parent",
    "reunited with a friend",
    "was betrayed by someone close",
    "received an award",
    "lost a valuable possession",
    "discovered a hidden talent",
    "faced legal trouble",
    "overcame an addiction",
    "experienced a life-changing revelation",
    "was promoted at work",
    "failed an important exam",
    "volunteered for a cause",
    "was publicly humiliated",
    "inherited a fortune",
    "moved back home",
    "was laid off",
    "celebrated a milestone",
    "survived an assault",
    "started a new hobby",
    "published a book",
    "lost a close friend",
    "adopted a child",
    "survived a surgery",
    "became famous overnight",
    "lost everything in a fire",
    "discovered a family secret",
    "moved to another country",
    "was wrongfully accused",
    "started a charity",
    "experienced a spiritual awakening",
    "was stranded in a foreign place",
    "won a competition",
    "faced a public scandal",
    "reconnected with a lost love",
    "was evicted from home",
    "achieved a lifelong dream",
    "suffered a major injury",
    "became a caregiver",
    "was scammed",
    "started a new relationship",
    "ended a toxic relationship",
    "was recognized for bravery",
    "lost a significant opportunity",
    "moved to a rural area",
    "was involved in a lawsuit",
    "discovered a new passion",
    "faced discrimination",
    "survived a kidnapping",
    "became homeless",
    "was honored in community",
    "experienced a career setback",
    "adopted a new lifestyle"
];

export const commonList = [
    "---DAILY ROUTINES---",
    "go to sleep",
    "wake up",
    "get dressed",
    "eat breakfast",
    "eat lunch",
    "eat dinner",
    "drink water",
    "drink something warm",
    "make tea",
    "make the bed",
    "follow the schedule",
    "skip the routine",
    "repeat the routine",
    "forget the routine",
    "take a break",
    "take a rest",
    "yawn quietly",
    "brush teeth",
    "take a shower",
    "comb hair",
    "apply lotion",
    "eat a snack",
    "drink coffee",
    "brew coffee",
    "set an alarm",
    "snooze the alarm",
    "stretch in the morning",
    "prepare for bed",
    "change pajamas",
    "floss teeth",
    "rinse mouth",
    "pack a lunch",
    "check the weather",
    "choose an outfit",
    "---MOVEMENT AND POSITIONING---",
    "go outside",
    "come inside",
    "walk away",
    "run away",
    "step back",
    "move closer",
    "pace in circles",
    "crouch low",
    "kneel down",
    "climb upward",
    "step down",
    "jump up",
    "sit down",
    "stand still",
    "lie down",
    "stretch out",
    "go for a walk",
    "follow the path",
    "stay on track",
    "dance around",
    "jog lightly",
    "sprint forward",
    "tiptoe quietly",
    "lean forward",
    "bend backward",
    "shuffle sideways",
    "hop in place",
    "slide across",
    "roll over",
    "spin around",
    "balance on one foot",
    "crawl slowly",
    "skip happily",
    "march in step",
    "sway gently",
    "lunge forward",
    "pivot quickly",
    "wander aimlessly",
    "---OBSERVATION AND ATTENTION---",
    "look around",
    "gaze outside",
    "turn away",
    "stare silently",
    "glance quickly",
    "stare at the sky",
    "watch the stars",
    "listen carefully",
    "notice a detail",
    "overlook a detail",
    "stay focused",
    "break concentration",
    "daydream a little",
    "scan the horizon",
    "peer closely",
    "squint at something",
    "watch the clouds",
    "observe the crowd",
    "eavesdrop quietly",
    "track movement",
    "study a map",
    "spot a bird",
    "hear a noise",
    "focus on a sound",
    "inspect carefully",
    "lose focus",
    "recall a sight",
    "blink slowly",
    "---OBJECT INTERACTION---",
    "open a door",
    "close a door",
    "lock the entrance",
    "unlock the entrance",
    "open a window",
    "close a window",
    "turn on the light",
    "turn off the light",
    "light a lantern",
    "blow out a flame",
    "sit by the fire",
    "pack a bag",
    "unpack supplies",
    "put something down",
    "pick something up",
    "drop something",
    "throw something",
    "catch something",
    "open a box",
    "close a box",
    "tie something up",
    "untie something",
    "sharpen a tool",
    "reach the knife",
    "break something",
    "hold item",
    "steal item",
    "set the fire",
    "extinguish the fire",
    "flip a switch",
    "plug in a device",
    "unplug a cord",
    "adjust a chair",
    "move a table",
    "stack books",
    "fold a blanket",
    "hang a picture",
    "light a candle",
    "pour a liquid",
    "stir a mixture",
    "cut a rope",
    "hammer a nail",
    "screw a bolt",
    "polish a surface",
    "lift a weight",
    "push a cart",
    "pull a handle",
    "twist a knob",
    "shake an object",
    "arrange flowers",
    "seal an envelope",
    "tear a paper",
    "---HOUSEHOLD AND MAINTENANCE TASKS---",
    "tidy the space",
    "wash up",
    "sweep the floor",
    "organize supplies",
    "clean the room",
    "water a plant",
    "pick a flower",
    "prepare something to eat",
    "wash the dishes",
    "fold clothes",
    "vacuum the carpet",
    "dust the shelves",
    "mop the floor",
    "scrub a stain",
    "empty the trash",
    "sort laundry",
    "iron clothes",
    "clean a mirror",
    "prune a bush",
    "rake leaves",
    "wipe a counter",
    "polish silverware",
    "organize a drawer",
    "sanitize a surface",
    "replace a bulb",
    "fix a leak",
    "paint a wall",
    "hang curtains",
    "---COMMUNICATION AND EXPRESSION---",
    "whisper something",
    "speak clearly",
    "remain silent",
    "hum a tune",
    "sing a melody",
    "sigh softly",
    "smile faintly",
    "laugh out loud",
    "cry quietly",
    "scream suddenly",
    "write a message",
    "send a message",
    "send a photo",
    "send a video",
    "dial a number",
    "shout loudly",
    "murmur softly",
    "giggle nervously",
    "sob gently",
    "cheer enthusiastically",
    "whistle a tune",
    "clap hands",
    "wave hello",
    "nod in agreement",
    "shake head",
    "point at something",
    "call someone’s name",
    "record a voice",
    "reply to a text",
    "forward an email",
    "post a comment",
    "share a story",
    "gesture broadly",
    "wink playfully",
    "---COGNITIVE AND PLANNING ACTIVITIES---",
    "write in a journal",
    "read a note",
    "sketch something",
    "draw something",
    "check the time",
    "mark a calendar",
    "make a list",
    "make a decision",
    "hesitate briefly",
    "avoid a choice",
    "choose something",
    "ignore something",
    "remember something",
    "forget something",
    "double-check something",
    "change the plan",
    "stick to the plan",
    "finish a task",
    "delay a task",
    "start over",
    "brainstorm ideas",
    "plan a route",
    "review a schedule",
    "set a goal",
    "prioritize tasks",
    "outline a project",
    "solve a puzzle",
    "memorize a fact",
    "analyze a problem",
    "reflect quietly",
    "imagine a scenario",
    "question a choice",
    "reconsider a plan",
    "estimate time",
    "calculate a cost",
    "organize thoughts",
    "jot down notes",
    "cross off a task",
    "---TIME AND SCHEDULING---",
    "arrive early",
    "arrive late",
    "leave early",
    "leave late",
    "stay home",
    "wait quietly",
    "schedule a meeting",
    "cancel a plan",
    "reschedule an event",
    "rush to leave",
    "linger longer",
    "set a timer",
    "check a deadline",
    "extend a stay",
    "shorten a visit",
    "plan a trip",
    "---SUBSTANCE USE---",
    "light a cigarette",
    "take a drag on cigarette",
    "finish a cigarette",
    "take a sip of alcohol",
    "pour a drink",
    "sip a cocktail",
    "light a pipe",
    "inhale smoke",
    "open a bottle",
    "cork a bottle",
    "---DIGITAL ACTIVITIES---",
    "browse the internet",
    "check email",
    "scroll through feeds",
    "like a post",
    "share a link",
    "download a file",
    "upload a photo",
    "watch a video",
    "search online",
    "update a profile",
    "log into an account",
    "log out",
    "refresh a page",
    "click a link",
    "save a bookmark",
    "---PERSONAL ACTIVITIES---",
    "masturbate",
    "take a deep breath",
    "meditate briefly",
    "stretch muscles",
    "apply makeup",
    "trim nails",
    "brush hair",
    "tie a ponytail",
    "shave face",
    "moisturize skin",
    "relax in a bath",
    "practice yoga",
    "count breaths",
    "close eyes",
    "hum softly"
];

export const targetList = [
    "---AFFECTIONATE ACTIONS---",
    "pat {target}",
    "pet {target}",
    "stroke {target}",
    "soothe {target}",
    "calm {target}",
    "comfort {target}",
    "hug {target}",
    "be kind to {target}",
    "be gentle to {target}",
    "be nice to {target}",
    "be friendly to {target}",
    "give gift to {target}",
    "share with {target}",
    "lend {target} something",
    "help {target} out",
    "do favors for {target}",
    "surprise {target}",
    "make {target} happy",
    "snuggle next to {target}",
    "cuddle up next to {target}",
    "tickle {target} playfully",
    "hold hands with {target}",
    "squeeze {target} gently",
    "offer a shoulder to {target}",
    "warm {target} with a blanket",
    "share a snack with {target}",
    "carry {target}'s bag",
    "compliment {target}",
    "cheer up {target}",
    "make {target} smile",
    "escort {target} home",
    "greet {target} warmly",
    "wave at {target}",
    "share a laugh with {target}",
    "offer {target} a seat",
    "help {target} stand",
    "guide {target} gently",
    "protect {target} from harm",
    "---ROMANTIC/INTIMATE ACTIONS---",
    "kiss {target}",
    "whisper in ear of {target}",
    "gaze lovingly at {target}",
    "stare into eyes of {target}",
    "look at {target} adoringly",
    "admire {target}",
    "adore {target}",
    "have a crush on {target}",
    "have feelings for {target}",
    "develop romantic feelings towards {target}",
    "take {target} to the movies",
    "go out with {target}",
    "take a walk with {target}",
    "have a picnic with {target}",
    "plan date nights with {target}",
    "surprise {target} with flowers",
    "buy gifts for {target}",
    "throw party for {target}",
    "celebrate special occasions with {target}",
    "be intimate with {target}",
    "write a love note to {target}",
    "dance slowly with {target}",
    "cook dinner for {target}",
    "watch a sunset with {target}",
    "plan a getaway with {target}",
    "sing to {target}",
    "dedicate a song to {target}",
    "hold {target} close",
    "caress {target}'s face",
    "share a drink with {target}",
    "stroll hand-in-hand with {target}",
    "surprise {target} with breakfast",
    "plan a romantic evening with {target}",
    "gaze at stars with {target}",
    "write poetry for {target}",
    "renew vows with {target}",
    "propose to {target}",
    "embrace {target} tightly",
    "cherish {target}'s presence",
    "---SUPPORTIVE ACTIONS---",
    "talk to {target}",
    "listen to {target}",
    "understand {target}",
    "console {target}",
    "make up with {target}",
    "support {target}",
    "encourage {target}",
    "trust {target}",
    "believe in {target}",
    "motivate {target}",
    "inspire {target}",
    "reassure {target}",
    "advise {target}",
    "mentor {target}",
    "stand by {target}",
    "defend {target}",
    "uplift {target}'s spirits",
    "praise {target}'s efforts",
    "validate {target}'s feelings",
    "back {target}'s decisions",
    "guide {target} through trouble",
    "share wisdom with {target}",
    "offer feedback to {target}",
    "cheer for {target}",
    "collaborate with {target}",
    "assist {target} with a task",
    "teach {target} something new",
    "learn from {target}",
    "---PHYSICAL POSITIONING ACTIONS---",
    "sit on {target}",
    "stand on {target}",
    "stand over {target}",
    "lean against {target}",
    "rest head on {target}",
    "sleep on {target}",
    "lie beside {target}",
    "spoon with {target}",
    "rest feet on {target}",
    "wrap arms around {target}",
    "lean head on {target}'s shoulder",
    "sit beside {target}",
    "stand next to {target}",
    "kneel beside {target}",
    "rest against {target}'s back",
    "climb over {target}",
    "face {target} closely",
    "curl up with {target}",
    "---AGGRESSIVE ACTIONS---",
    "kick {target}",
    "punch {target}",
    "hit {target}",
    "slap {target}",
    "push {target}",
    "shove {target}",
    "knock over {target}",
    "trip {target}",
    "stumble {target}",
    "make {target} fall",
    "step on {target}",
    "crush {target}",
    "grab {target} roughly",
    "shake {target} hard",
    "pin {target} down",
    "tackle {target}",
    "throw {target} aside",
    "drag {target} forcefully",
    "slam {target} against a wall",
    "headbutt {target}",
    "elbow {target}",
    "knee {target} in the stomach",
    "stomp on {target}'s foot",
    "choke {target} briefly",
    "push {target} into water",
    "flip {target} over",
    "---HARMFUL/ABUSIVE ACTIONS---",
    "suffocate {target}",
    "drown {target}",
    "strangle {target}",
    "torture {target}",
    "torment {target}",
    "humiliate {target}",
    "mock {target}",
    "tease {target}",
    "ridicule {target}",
    "belittle {target}",
    "insult {target}",
    "degrade {target}",
    "embarrass {target}",
    "make fun of {target}",
    "laugh at expense of {target}",
    "bully {target}",
    "scare {target}",
    "frighten {target}",
    "torment {target} with cruel words",
    "spread rumors about {target}",
    "gossip about {target}",
    "mock {target}'s appearance",
    "make fun of {target}'s clothes",
    "yell at {target}",
    "scream at {target}",
    "shout at {target}",
    "berate {target}",
    "scold {target}",
    "lecture {target}",
    "criticize {target}",
    "judge {target}",
    "condemn {target}",
    "blame {target}",
    "accuse {target}",
    "threaten {target}",
    "mock {target}'s fears",
    "exploit {target}'s vulnerabilities",
    "take advantage of {target}",
    "manipulate {target}",
    "deceive {target}",
    "lie to {target}",
    "cheat on {target}",
    "betray {target}",
    "backstab {target}",
    "stab in the back",
    "plot against {target}",
    "conspire against {target}",
    "sabotage {target}'s plans",
    "destroy {target}'s property",
    "ruin {target}'s reputation",
    "blackball {target}",
    "ostracize {target}",
    "make fun of {target} in public",
    "humiliate {target} in public",
    "mock {target}'s feelings",
    "hurt {target}'s feelings",
    "be cruel to {target}",
    "gaslight {target}",
    "shame {target} publicly",
    "slander {target}",
    "defame {target}",
    "exclude {target} deliberately",
    "ignore {target}'s pleas",
    "taunt {target} relentlessly",
    "harass {target} online",
    "spread lies about {target}",
    "blackmail {target}",
    "coerce {target} into compliance",
    "undermine {target}'s confidence",
    "belittle {target}'s achievements",
    "mock {target}'s dreams",
    "disrespect {target}'s boundaries",
    "violate {target}'s privacy",
    "steal from {target}",
    "vandalize {target}'s belongings",
    "provoke {target} intentionally",
    "alienate {target} from friends",
    "isolate {target} socially",
    "curse at {target}",
    "spit at {target}",
    "throw something at {target}",
    "intimidate {target} with gestures",
    "stalk {target} secretly"
];

export const dillemaList = [
    "---PERSONAL DILEMMAS---",
    "lies to protect a friend",
    "steals to feed family",
    "forgives a betrayal",
    "keeps a painful secret",
    "reveals a friend’s secret",
    "cheats to win a game",
    "helps a stranger in need",
    "ignores a plea for help",
    "sacrifices personal gain for honesty",
    "hides a mistake from family",
    "confronts a loved one’s wrongdoing",
    "chooses loyalty over truth",
    "breaks a promise to avoid harm",
    "keeps silent about a crime",
    "takes blame for another’s mistake",
    "refuses to forgive a wrong",
    "shares a limited resource",
    "hoards supplies during scarcity",
    "admits to a personal fault",
    "denies responsibility for a mistake",
    "hides an affair from a partner",
    "confesses to infidelity",
    "borrows money without repaying",
    "spreads a lie to avoid shame",
    "helps a friend hide evidence",
    "betrays a family member’s trust",
    "uses a fake identity for gain",
    "forgives a repeated offense",
    "cuts ties with a toxic friend",
    "keeps stolen goods for personal use",
    "returns stolen property anonymously",
    "lies to avoid hurting feelings",
    "---SOCIAL DILEMMAS---",
    "reports a witnessed crime",
    "ignores an act of injustice",
    "stands up to a bully",
    "spreads a damaging rumor",
    "defends a controversial opinion",
    "joins a protest for a cause",
    "stays silent during injustice",
    "helps a marginalized person",
    "excludes someone from a group",
    "challenges unfair rules",
    "follows unjust social norms",
    "speaks out against discrimination",
    "benefits from unfair privilege",
    "organizes aid for a community",
    "takes credit for group work",
    "exposes a public lie",
    "spreads misinformation for gain",
    "intervenes in a public dispute",
    "avoids involvement in conflict",
    "supports a divisive leader",
    "vandalizes public property in protest",
    "reports a neighbor’s illegal activity",
    "joins a mob for a cause",
    "refuses to join a boycott",
    "donates to an unethical charity",
    "outs a whistleblower for loyalty",
    "steals from a community fund",
    "protects a group’s harmful secret",
    "exposes a cult’s practices",
    "participates in illegal gambling",
    "shuns a reformed offender",
    "supports vigilante justice",
    "---PROFESSIONAL DILEMMAS---",
    "whistleblows on workplace corruption",
    "follows unethical orders",
    "takes credit for a colleague’s work",
    "covers up a workplace mistake",
    "reports a coworker’s misconduct",
    "ignores a safety violation",
    "falsifies records for profit",
    "refuses a bribe",
    "accepts a bribe for silence",
    "prioritizes profit over safety",
    "challenges an unfair boss",
    "complies with harmful policies",
    "leaks confidential information",
    "protects sensitive client data",
    "cuts corners to meet deadlines",
    "upholds professional integrity",
    "manipulates data for a promotion",
    "helps a struggling coworker",
    "sabotages a rival’s project",
    "discloses a conflict of interest",
    "embezzles company funds",
    "ignores a coworker’s harassment",
    "fakes qualifications for a job",
    "exposes a client’s fraud",
    "engages in insider trading",
    "hides a financial discrepancy",
    "uses company resources for personal gain",
    "reports a supervisor’s theft",
    "follows orders to falsify taxes",
    "refuses to sign a false report",
    "covers up a product defect",
    "blows the whistle on unsafe practices",
    "---MORAL CONFLICTS---",
    "chooses family over duty",
    "sacrifices for a stranger’s safety",
    "betrays a trust for justice",
    "upholds a principle despite harm",
    "breaks a law to save a life",
    "obeys a law despite moral objection",
    "prioritizes self-preservation over duty",
    "risks life for a moral cause",
    "deceives to achieve a greater good",
    "tells the truth despite consequences",
    "harms one to save many",
    "refuses to harm despite pressure",
    "judges others for moral failings",
    "forgives others despite wrongs",
    "seeks revenge for injustice",
    "shows mercy to an enemy",
    "violates a vow for a cause",
    "keeps a vow despite temptation",
    "chooses silence over justice",
    "acts against personal beliefs",
    "steals medicine for a sick child",
    "turns in a fugitive friend",
    "harbors an escaped convict",
    "lies under oath to protect someone",
    "tells the truth in court despite risk",
    "prioritizes wealth over ethics",
    "donates stolen money to charity",
    "refuses to aid a corrupt official",
    "helps a criminal escape punishment",
    "exposes a friend’s corruption",
    "ignores a moral duty for convenience",
    "takes a life to prevent greater harm",
    "---ILLEGAL ACTIVITY DILEMMAS---",
    "sells illegal drugs for profit",
    "buys drugs to cope with stress",
    "smuggles goods across borders",
    "launders money for a friend",
    "hacks a system for justice",
    "steals data for personal gain",
    "commits arson to send a message",
    "bribes an official for favors",
    "forgers documents for a cause",
    "hides stolen loot from authorities",
    "drives under the influence",
    "shoplifts to survive",
    "commits tax evasion for wealth",
    "reports a partner’s illegal dealings",
    "blackmails someone for leverage",
    "extorts money from a business",
    "plants evidence to frame someone",
    "destroys evidence to protect a loved one",
    "engages in illegal arms trading",
    "participates in a heist",
    "refuses to testify against a criminal",
    "aids in a bank robbery",
    "fences stolen goods for income",
    "hacks into a rival’s system",
    "traffics counterfeit money",
    "helps a fugitive evade capture",
    "commits perjury to save a friend",
    "exposes an illegal operation",
    "joins a criminal syndicate",
    "refuses to join a gang",
    "steals intellectual property",
    "sells pirated software",
    "ignores a smuggling operation"
];

export const abstractList = [
    "---ABSTRACT THINKING---",
    "ponders a question",
    "analyzes a problem",
    "reflects on a memory",
    "questions a belief",
    "weighs multiple options",
    "synthesizes new ideas",
    "doubts a conclusion",
    "seeks deeper understanding",
    "reconsiders a perspective",
    "constructs a theory",
    "dissects an argument",
    "imagines a scenario",
    "evaluates consequences",
    "anticipates outcomes",
    "deconstructs assumptions",
    "forms a hypothesis",
    "recalls a concept",
    "clarifies a thought",
    "challenges a notion",
    "connects disparate ideas",
    "---EMOTIONAL PROCESSING---",
    "grapples with guilt",
    "embraces fleeting joy",
    "suppresses rising anger",
    "nurtures inner peace",
    "confronts buried fear",
    "savors quiet contentment",
    "wrestles with doubt",
    "releases pent-up sorrow",
    "cultivates hope",
    "processes lingering grief",
    "harbors unspoken resentment",
    "fosters self-compassion",
    "overcomes nagging insecurity",
    "channels intense passion",
    "accepts painful truth",
    "resists overwhelming despair",
    "cherishes a moment of pride",
    "soothes inner turmoil",
    "rekindles faded empathy",
    "navigates emotional conflict",
    "---PHILOSOPHICAL REFLECTION---",
    "contemplates existence",
    "seeks life's purpose",
    "questions moral boundaries",
    "ponders free will",
    "reflects on mortality",
    "explores spiritual meaning",
    "wonders about destiny",
    "debates ethical principles",
    "searches for truth",
    "considers cosmic significance",
    "examines personal values",
    "grapples with fate",
    "muses on human nature",
    "reflects on justice",
    "questions societal norms",
    "ponders eternal truths",
    "seeks universal harmony",
    "contemplates self-identity",
    "weighs life's contradictions",
    "explores existential doubt",
    "---CREATIVE IMAGINATION---",
    "envisions a new world",
    "dreams of impossible futures",
    "invents a fictional tale",
    "weaves a poetic vision",
    "imagines a utopian society",
    "sketches a surreal scene",
    "crafts a symbolic metaphor",
    "fantasizes about adventure",
    "conceives an original idea",
    "visualizes abstract forms",
    "spins a narrative thread",
    "creates a mental masterpiece",
    "dreams in vivid colors",
    "constructs a fantasy realm",
    "explores uncharted concepts",
    "imagines alternate realities",
    "fashions a mythical story",
    "envisions a bold innovation",
    "weaves a tapestry of thoughts",
    "conjures a visionary dream"
];